server:
  servlet: {context-path: /}
  port: 8090
spring:
  datasource: {driver-class-name: com.mysql.jdbc.Driver, password: zw123, type: com.alibaba.druid.pool.DruidDataSource,
    url: 'jdbc:mysql://localhost:3306/db_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false',
    username: root}
  resources: {static-locations: 'classpath:/static/'}
  thymeleaf: {cache: false, content-type: text/html, mode: HTML5, prefix: 'classpath:/templates/',
    suffix: .html}
redis:
  host: 127.0.0.1
  password: ''
  port: 6379
  jedis:
    pool: {max-active: 20, max-idle: 8, min-idle: 0, max-wait: 2000}
logging:
  level: {ssm.app.mapper: debug}
