spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: zw123
    type: com.alibaba.druid.pool.DruidDataSource
    url: 'jdbc:mysql://localhost:3306/db_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false'
    username: root
  resources: 
    static-locations: 'classpath:/static/'
  thymeleaf: 
    cache: false
    content-type: text/html
    mode: HTML5
    prefix: 'classpath:/templates/'
    suffix: .html